= Umari Data Filter Starter
:toc:
:toc-title: Índice
:sectnums:

Projeto Starter Spring Boot com API para filtragem de dados e operações de agregção

== Instalação

Como primeiro passo é necessário a inclusão da depedência *umari-datafilter-spring-boot-starter* no `pom.xml`

[source,xml]
----
<dependency>
    <groupId>umari.datafilter</groupId>
    <artifactId>umari-datafilter-spring-boot-starter</artifactId>
    <version>1.0.0</version>
</dependency>
----

=== Definição do banco de dados.

IMPORTANT: Para o correta utilização do projeto é necessário definir a chave `spring.datasource.driver-class-name` no arquivo
`application.properties`

.H2
[source,properties]
----
spring.datasource.driver-class-name=org.h2.Driver
----

.Oracle
[source,properties]
----
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
----

.MySql
[source,properties]
----
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
----

.Postgre
[source,properties]
----
spring.datasource.driver-class-name=org.postgresql.Driver
----

== Interface UdfTemplate

Todas as operações de filtragem e agregação estão disponível através da interface *UdfTemplate*. Segue abaixo
os métodos disponíveis:

.UdfTemplate.java
[source, java, linenums]
----
public interface UdfTemplate {

    /**
     * Realiza a filtragem de dados para a entidade
     *
     * @param entityClass Entidade alvo da filtragem.
     * @param filterable  Lista de predicados.
     * @param pageable    Dados de paginação e ordenação.
     * @return Objeto paginado (Page) com as informações de filtragem.
     */
    <T> Page<T> filter(Class<T> entityClass, Filterable filterable, Pageable pageable);

    /**
     * Realiza a filtragem de dados com paginação para a entidade com suporte a specification.
     *
     * @param entityClass
     * @param filterable
     * @param pageable
     * @param specification
     * @param <T>
     * @return
     */
    <T> Page<T> filter(Class<T> entityClass, Filterable filterable, Pageable pageable, Specification<T> specification);

    /**
     * Realiza uma operação de filtragem com paginação em SQL nativo.
     *
     * @param sql
     * @param filterable
     * @param pageable
     * @return
     */
    Page<List<Map<String, Object>>> filter(String sql, Filterable filterable, Pageable pageable);

    /**
     * Realiza uma operação de filtragem sem paginação em SQL nativo.
     *
     * @param sql
     * @param sort
     * @param filter
     * @return
     */
    List<Map<String, Object>> filter(String sql, Sort sort, Filterable filter);

    /**
     * Realiza a operação(s) de agregação na entidade.
     *
     * @param entityClass
     * @param filterable
     * @param <T>
     * @return
     */
    <T> List<Aggregation> aggregate(Class<T> entityClass, Filterable filterable, Aggregable[] aggregables);

    /**
     * Realiza a operação(s) de agregação na entidade com suporte a specification.
     *
     * @param entityClass
     * @param filterable
     * @param aggregables
     * @param specification
     * @param <T>
     * @return
     */
    <T> List<Aggregation> aggregate(Class<T> entityClass, Filterable filterable, Aggregable[] aggregables, Specification<T> specification);

    /**
     * Realiza operação(s) de agregação em SQL nativo.
     *
     * @param sql
     * @param filterable
     * @param aggregables
     * @return
     */
    List<Aggregation> aggregate(String sql, Filterable filterable, Aggregable[] aggregables);

}
----

== Definição do(s) endpoint(s) Rest

TIP: Por conveção todos os endoint rest de filtragem e agregação devem ser definidos dentro do pacote
`rest.udf`.

Para a classes JPA

.PessoaUdfRest.java
[source, java, linenums]
----
package foo.rest.udf;

import foo.domain.Pessoa;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import umari.datafilter.core.Aggregable;
import umari.datafilter.core.UdfRequest;
import umari.datafilter.service.UdfTemplate;

@RequestMapping("/api/udf/pessoa")
@RestController
public class PessoaUdfRest {

    @Autowired
    private UdfTemplate udfTemplate;

    /**
     * Endpoint para requisições de filtragem para a entidade Pessoa.
     *
     * @param udfRequest
     * @param pageable
     * @return
     */
    @PostMapping
    public ResponseEntity<Page<?>> filter(@RequestBody UdfRequest udfRequest, Pageable pageable) {
        return ResponseEntity.ok(udfTemplate.filter(
                Pessoa.class,
                udfRequest.getFilterable(),
                pageable));
    }

    /**
     * Endpoint para requisições de agregação para a entidade Pessoa
     *
     * Exemplo de JSON de requisição para operação de count.
     * <pre>
     * {
     * 	"aggregables" : [
     * 	    {
     * 		"selector": "id",
     * 		"operation": "count"
     *      }
     *   ]
     * }
     * </pre>
     *
     * @param udfRequest
     * @return
     */
    @PostMapping("/agg")
    public ResponseEntity<?> aggreate(@RequestBody UdfRequest udfRequest) {
        return ResponseEntity.ok(udfTemplate.aggregate(
                Pessoa.class,
                udfRequest.getFilterable(),
                udfRequest.getAggregables().toArray(new Aggregable[]{})));

    }
}

----